<a href="https://colab.research.google.com/github/waraporn19/Project_2021_matchingcolor/blob/main/Test_datapoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import cv2
import numpy as np

In [ ]:
!pip install azure-storage-blob==2.1.0

     |████████████████████████████████| 88 kB 4.9 MB/s 
     |████████████████████████████████| 47 kB 4.8 MB/s 
     |████████████████████████████████| 3.6 MB 30.8 MB/s 


In [ ]:
from azure.storage.blob import BlockBlobService
import os
blob_service_client = BlockBlobService(account_name='dent01', account_key='CuShY0B4TZJ84TjzPpaHxyrHOpO73aGXeCpdVq7x26OjIlQ1HOz+3DVc9pDEj9BdcEL8odFuTRF0mOAE+aCgiw==')

In [ ]:
img = 'D31A6339-9324-4718-8F1D-F9C86FF1CAC1.png'

In [ ]:
list_total1 = list()
list_total2 = list()
list_total3 = list()
S5_double = img
full_path_to_file2 = os.path.join(S5_double) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(S5_double)
S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131] #ลองดูพิกัดใหม่
S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
S5meanrefA1_1 = np.array(S5meanrefA1_1[0])
S5meanA1_2 = np.array(S5meanA1_2[0])
S5rgbrefA1_1 = list()
S5rgbA1_2 = list()
for i in range(3):
  S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
  S5rgbA1_2.append(S5meanA1_2[:,i].mean())
list_total1.append(S5rgbrefA1_1)
list_total2.append(S5rgbA1_2)
list_total1[0].extend(list_total2[0])
list_total3 = list_total1 

In [ ]:
list_total3

[[227.6875,
  208.63392857142858,
  171.67857142857142,
  227.53846153846155,
  208.3846153846154,
  171.48461538461538]]

In [ ]:
S5rgbrefA1_1

[227.6875,
 208.63392857142858,
 171.67857142857142,
 227.53846153846155,
 208.3846153846154,
 171.48461538461538]

In [ ]:
list_total3

[[227.6875,
  208.63392857142858,
  171.67857142857142,
  227.53846153846155,
  208.3846153846154,
  171.48461538461538]]

In [ ]:
S5meanrefA1_1.shape

In [ ]:
G1[0]

In [ ]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#     for j in range(S5RGB_imgA1A1_1.shape[1]): 
#           if 1769<i<1881 and 2019<j<2131 :
#              new_img = S5RGB_imgA1A1_1[i][j]
#           if 1770<i<1880 and 2015<j<2145 :
#              new_img = S5RGB_imgA1A1_1[i][j]
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [ ]:
new_img

In [ ]:
S5RGB_imgA1A1_1.shape

In [ ]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#   for j in range(S5RGB_imgA1A1_1.shape[1]): 
#       if 1769<i<1881 and 2019<j<2131 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j]) 
#       if 1770<i<1880 and 2015<j<2145 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j])
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [ ]:
S5meanrefA1_1

In [ ]:
S5meanrefA1_1.shape

In [ ]:
list_total12 = list()
list_total22 = list()
S5_double2 = img
image2  = cv2.imread(S5_double2) #RGB
S1RGB_imgA1A1_12= cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)
S1meanrefA1_12 = list()
for i in range(S1RGB_imgA1A1_12.shape[0]): 
  for j in range(S1RGB_imgA1A1_12.shape[1]): 
        if 1769<i<1881 and 2019<j<2131 :
          S1meanrefA1_12.append(S1RGB_imgA1A1_12[i][j]) 
S1meanrefA1_12 = np.array(S1meanrefA1_12)
S1rgbrefA1_12 = list()
for i in range(3):
   S1rgbrefA1_12.append(S1meanrefA1_12[:,i].mean())
list_total12.append(S1rgbrefA1_12)

S1meanA1_22 = list()
for i in range(S1RGB_imgA1A1_12.shape[0]): 
  for j in range(S1RGB_imgA1A1_12.shape[1]): 
      if 1770<i<1880 and 2015<j<2145 :
        S1meanA1_22.append(S1RGB_imgA1A1_12[i][j])  
S1meanA1_22 = np.array(S1meanA1_22)
# S1rgbA1_2 = list()
# for i in range(3):
#   S1rgbA1_2.append(S1meanA1_2[:,i].mean())
# list_total2.append(S1rgbA1_2)
# list_total1[0].extend(list_total2[0])
# list_total3 = list_total1

In [ ]:
list_total3 

In [ ]:
S1meanrefA1_12

In [ ]:
S1meanrefA1_12.shape

In [ ]:
# list_total1 = list()
# for img in A1_set11['Img']:
#   S1_double = img
#   full_path_to_file2 = os.path.join(S1_double) 
#   blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
#   imgS1_A1A1_1  = cv2.imread(S1_double) #RGB
#   S1RGB_imgA1A1_1= cv2.cvtColor(imgS1_A1A1_1, cv2.COLOR_BGR2RGB)
#   S1meanrefA1_1 = list()
#   S1meanrefA1_2 = list()
#   for i in range(S1RGB_imgA1A1_1.shape[0]): 
#      for j in range(S1RGB_imgA1A1_1.shape[1]): 
#                 if 1769<i<1881 and 2019<j<2131 :
#                   S1meanrefA1_1.append(S1RGB_imgA1A1_1[i][j]) 
#                 if 1770<i<1880 and 2015<j<2145 :
#                   S1meanrefA1_2.append(S1RGB_imgA1A1_1[i][j])
#   S1meanrefA1_1 = np.array(S1meanrefA1_1)
#   S1meanrefA1_2 = np.array(S1meanrefA1_2)
#   S1rgbrefA1_1 = list()
#   S1rgbrefA1_2 = list()
#   for i in range(3):
#     S1rgbrefA1_1.append(S1meanrefA1_1[:,i].mean())
#     S1rgbrefA1_2.append(S1meanrefA1_2[:,i].mean())
#   list_total1.append((S1rgbrefA1_1,S1rgbrefA1_2))

In [ ]:
S5_double = img
full_path_to_file2 = os.path.join(S5_double) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(S5_double)
S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)

S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  
S5meanA1_2 = S5RGB_imgA1A1_1[1771:1880,2016:2145]
S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
S5refA1_2 = np.reshape(S5meanA1_2,(109*129, 3))
S5refA1_3 = np.array(S5refA1_1)
S5refA1_4 = np.array(S5refA1_2)
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()
R = S5refA1_2[:,0].mean()
G = S5refA1_2[:,1].mean()
B = S5refA1_2[:,2].mean()

list_total = list()
list_total.append(Rref)
list_total.append(Gref)
list_total.append(Bref)
list_total.append(R)
list_total.append(G)
list_total.append(B)


In [ ]:
print("Rref:", Rref)
print("Gref:", Gref)
print("Bref:", Bref)
print("R:", R)
print("G:", G)
print("B:", B)

In [ ]:
list_total

In [ ]:
list_total2 = list()
list_total2.append(list_total)

In [ ]:
list_total2

#ตาราง

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

In [ ]:
path = '/content/drive/My Drive/shadeimg/SVM shade'

In [ ]:
import os

In [ ]:
os.listdir(path)

In [ ]:
AA = os.path.join(path,'Color-checkerDD.xlsx')

In [ ]:
A1_set1= pd.read_excel(AA, sheet_name='D3_1')
A1_set1

In [ ]:
A1_set1.rename(columns={"รหัสเฉดไกด์": "Ref"},inplace=True)

In [ ]:
A1_set1.rename(columns={"Unnamed: 2":"Shad"},inplace=True)

In [ ]:
A1_set1.rename(columns={"ชื่อไฟล์ข้อมูล":"Img"},inplace=True)

In [ ]:
A1_set1 = A1_set1.iloc[3:162,:]

In [ ]:
table1= A1_set1[['Ref', 'Shad','Img']]
table1

In [ ]:
A1_set11 = A1_set1
A1_set11

In [ ]:
import pandas as pd

In [ ]:
for img in A1_set11['Img']:
    S5_double = img
    full_path_to_file2 = os.path.join(S5_double) 
    blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
    imagee = cv2.imread(S5_double)
    S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)

    S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131]
    S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
    S5refA1_1 = np.array(S5meanrefA1_1[0])
    S5refA1_2 = np.array(S5meanA1_2[0])
    Rref = S5refA1_1[:,0].mean()
    Gref = S5refA1_1[:,1].mean()
    Bref = S5refA1_1[:,2].mean()
    R = S5refA1_2[:,0].mean()
    G = S5refA1_2[:,1].mean()
    B = S5refA1_2[:,2].mean()
    
    list_total = list()
    list_total.append(Rref)
    list_total.append(Gref)
    list_total.append(Bref)
    list_total.append(R)
    list_total.append(G)
    list_total.append(B)
    list_total2 = list()
    list_total2.append(list_total) 

In [ ]:
list_total2

In [ ]:
cols=['R-ref', 'G-ref' , 'B-ref', 'R-Shad', 'G-Shad', 'B-Shad']
S1=pd.DataFrame(list_total2,columns=cols)
S1['Setting']='Set1'
S1

In [ ]:
pd.concat([S1,table1], axis=1)

#test model 160 รูป

In [ ]:
#load model
import pickle
with open('Model_D3_V5.pkl', 'rb') as pickle_file :
      new_data = pickle.load(pickle_file )

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

In [ ]:
import os

In [ ]:
from sklearn import metrics

In [ ]:
from sklearn import datasets

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
path = '/content/drive/My Drive/shadeimg/SVM shade'

In [ ]:
CC1 = os.path.join(path,'D3Set5-61.xlsx')
print(CC1)

In [ ]:
table_D3CC1 = pd.read_excel(CC1 , sheet_name='D3Set51')
table_D3CC1.head()

In [ ]:
Set1 = os.path.join(path,'Setting1.xlsx')
print(Set1)

In [ ]:
Set2 = os.path.join(path,'Setting2.xlsx')
print(Set2)

In [ ]:
Set3 = os.path.join(path,'Setting3.xlsx')
print(Set3)

In [ ]:
Set4 = os.path.join(path,'Setting4.xlsx')
print(Set4)

In [ ]:
table_D3Set1 = pd.read_excel(Set1 , sheet_name='D3Set1')
table_D3Set1.head()

In [ ]:
table_D3Set2 = pd.read_excel(Set2, sheet_name='D3Set2')
table_D3Set2.head()

In [ ]:
table_D3Set3 = pd.read_excel(Set3, sheet_name='D3Set3 ')
table_D3Set3.head()

In [ ]:
table_D3Set4 = pd.read_excel(Set4, sheet_name='D3Set4')
table_D3Set4.head()

In [ ]:
RGB_D3_Set1_tt = table_D3CC1.drop(['H-ref','S-ref','V-ref','H-Shad','S-Shad','V-Shad','Setting','Ref','Shad','Img'], axis=1)

In [ ]:
clf=RandomForestClassifier()

In [ ]:
RGB_D3_Set4_w1 = table_D3Set4

RGB_D3_Set1_w1 = table_D3Set1

RGB_D3_Set2_w1 = table_D3Set2

RGB_D3_Set3_w1 = table_D3Set3

RGB_D3_concat0_w1 = pd.concat([RGB_D3_Set1_w1,RGB_D3_Set2_w1,RGB_D3_Set3_w1])

RGB_D3_concat1_w1 = pd.concat([RGB_D3_concat0_w1,RGB_D3_Set4_w1])
#รวมตารางของแต่ละ setting เข้าด้วยกันเพื่อใช้ในการ train ข้อมูล

RGB_D3_concat2_w1 = RGB_D3_concat1_w1.drop(['H-ref','S-ref','V-ref','H-Shad','S-Shad','V-Shad','Setting','Ref','Shad','Img'], axis=1)
#เอาเฉพาะตัวตารางที่เป็น RGB ออกมา

X_test_D3_RGB_w1 = np.array(RGB_D3_Set1_tt)

y_D3_RGB_w1 =  table_D3CC1.iloc[:,14:15]
#ใช้เฉพาะ column shad ในการจับคู่

y_test_D3_RGB_w1 = np.array(y_D3_RGB_w1)#เปลี่ยนให้ค่าในตารางเป็น array 

X_train_D3_RGB_w1 = np.array(RGB_D3_concat2_w1)#เปลี่ยนให้ค่าในตารางเป็น array 

y_train_D3RGB_w1 = RGB_D3_concat1_w1.iloc[:,14:15]#ใช้เฉพาะ column shad ในการจับคู่

y_train_D3_RGB_w1 = np.array(y_train_D3RGB_w1)#เปลี่ยนให้ค่าในตารางเป็น array 

y_train_D3_RGB_w1.shape = (len(y_train_D3_RGB_w1),)

In [ ]:
y_train_D3_RGB_w1

In [ ]:
clf.fit(X_train_D3_RGB_w1, y_train_D3_RGB_w1) #หาค่าเฉลี่ยและส่วนเบี่ยงเบนมาตราฐานของ x_train y_train

In [ ]:
y_pred_D3_RGB_w1 = clf.predict(X_test_D3_RGB_w1) #ทำการจับคู่สีฟันด้วยวิธี random forest โดยใช้ X_test

In [ ]:
metrics.accuracy_score(y_test_D3_RGB_w1, y_pred_D3_RGB_w1)

In [ ]:
import pickle
with open('Model_D3_V6.pkl', 'wb') as pickle_file :
       pickle.dump(clf, pickle_file )

In [ ]:
#load model
import pickle
with open('Model_D3_V6.pkl', 'rb') as pickle_file :
      new_data = pickle.load(pickle_file )

In [ ]:
print(new_data)

In [ ]:
img = 'B42D66D8-5C0A-40B1-AA84-00261E79E347.png' #A3

In [ ]:
img = '3C9EFF45-7D0C-49E3-88C4-C2C75ED8262C.png' #B4

In [ ]:
img = 'D3803668-F57C-4D0C-989F-A8B28512A28D.png' #A1

In [ ]:
img = 'F083945A-EC0A-4B4B-ABEA-8D2D838F071C.png' #C1

In [ ]:
img = '84BB9A93-0F2B-4BCE-AF1A-B27245EFC6C8.png' #D3

In [ ]:
img = '23117DA5-24D7-456F-BF3E-85F246E21BB8.png' #C2

In [ ]:
S5_double = img
full_path_to_file2 = os.path.join(S5_double) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(S5_double)
S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)

S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  
S5meanA1_2 = S5RGB_imgA1A1_1[1771:1880,2016:2145]
S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
S5refA1_2 = np.reshape(S5meanA1_2,(109*129, 3))
S5refA1_3 = np.array(S5refA1_1)
S5refA1_4 = np.array(S5refA1_2)
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()
R = S5refA1_2[:,0].mean()
G = S5refA1_2[:,1].mean()
B = S5refA1_2[:,2].mean()

list_total = list()
list_total.append(Rref)
list_total.append(Gref)
list_total.append(Bref)
list_total.append(R)
list_total.append(G)
list_total.append(B)


In [ ]:
list_total2 = list()
list_total2.append(list_total)

In [ ]:
predic_model= new_data.predict(list_total2)

In [ ]:
predic_model

#หาจุด หาค่า mean

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
img1 = '02F6E3F2-99BD-4CCA-9458-A0EBF9CE7F4D.png'
img2 = '3C9EFF45-7D0C-49E3-88C4-C2C75ED8262C.png'
img3 = '44F32CB2-4AC3-4AA4-B00C-0873A77C39FB.png'
img4 = '84BB9A93-0F2B-4BCE-AF1A-B27245EFC6C8.png'

In [ ]:
img= 'FAF5097E-1FEB-41DF-92C9-C190A88FE15F.png'
img1 = 'CD25F822-5A97-4F4A-8667-90D9F5C9CC62.png'
img2 ='B772B836-0F38-44D5-959C-675C592375FE.png'

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1803,1753:1756])
S5refA1_1 = np.reshape(SS1_RGBimg1,(3*3, 3))  
S5refA1_3 = np.array(S5refA1_1)
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()

list_total = list()
list_total.append(Rref)C
list_total.append(Gref)
list_total.append(Bref)

In [ ]:
SS1_RGBimg1

array([[[227, 209, 173],
        [228, 210, 174],
        [226, 208, 172]],

       [[227, 209, 173],
        [227, 209, 173],
        [226, 208, 172]],

       [[226, 208, 172],
        [226, 208, 172],
        [226, 208, 172]]], dtype=uint8)

In [ ]:
list_total

[226.55555555555554, 208.55555555555554, 172.55555555555554]

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1803,2050:2053])
S5refA1_1 = np.reshape(SS1_RGBimg1,(3*3, 3))  
S5refA1_3 = np.array(S5refA1_1)
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()

list_total = list()
list_total.append(Rref)
list_total.append(Gref)
list_total.append(Bref)

In [ ]:
SS1_RGBimg1

array([[[228, 202, 151],
        [226, 200, 149],
        [231, 205, 154]],

       [[229, 203, 152],
        [235, 209, 158],
        [235, 209, 158]],

       [[231, 205, 154],
        [234, 208, 157],
        [229, 203, 152]]], dtype=uint8)

In [ ]:
list_total

[230.88888888888889, 204.88888888888889, 153.88888888888889]

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1801,2050:2053])

In [ ]:
SS1_RGBimg1

array([[[228, 202, 151],
        [226, 200, 149],
        [231, 205, 154]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2050:2051])

In [ ]:
SS1_RGBimg1

array([[[229, 203, 152]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2051:2052])

In [ ]:
SS1_RGBimg1

array([[[235, 209, 158]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2052:2053])

In [ ]:
SS1_RGBimg1

array([[[235, 209, 158]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,2050:2051])

In [ ]:
SS1_RGBimg1

array([[[231, 205, 154]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,2051:2052])

In [ ]:
SS1_RGBimg1

array([[[234, 208, 157]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,2052:2053])

In [ ]:
SS1_RGBimg1

array([[[229, 203, 152]]], dtype=uint8)

In [ ]:
SS1_RGBimg1

array([[[227, 209, 173],
        [228, 210, 174],
        [226, 208, 172]],

       [[227, 209, 173],
        [227, 209, 173],
        [226, 208, 172]],

       [[226, 208, 172],
        [226, 208, 172],
        [226, 208, 172]]], dtype=uint8)

In [ ]:
list_total

[226.55555555555554, 208.55555555555554, 172.55555555555554]

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,1754:1755])

In [ ]:
SS1_RGBimg1

array([[[227, 209, 173],
        [228, 210, 174],
        [226, 208, 172]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img1
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1803,1750:1753])
S5refA1_1 = np.reshape(SS1_RGBimg1,(3*3, 3))  
S5refA1_3 = np.array(S5refA1_1)
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()

list_total = list()
list_total.append(Rref)
list_total.append(Gref)
list_total.append(Bref)

In [ ]:
SS1_RGBimg1

array([[[221, 198, 157],
        [222, 199, 158],
        [221, 198, 156]],

       [[221, 198, 157],
        [222, 199, 158],
        [225, 202, 160]],

       [[220, 197, 156],
        [222, 199, 158],
        [224, 201, 160]]], dtype=uint8)

In [ ]:
list_total

[222.0, 199.0, 157.77777777777777]

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img1
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1752:1753,1801:1802])

In [ ]:
SS1_RGBimg1

array([[[222, 199, 157]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img1
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1750:1751,1800:1801])

In [ ]:
SS1_RGBimg1

array([[[223, 200, 158]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img1
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1803,2050:2053])
S5refA1_1 = np.reshape(SS1_RGBimg1,(3*3, 3))  
S5refA1_3 = np.array(S5refA1_1)
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()

list_total = list()
list_total.append(Rref)
list_total.append(Gref)
list_total.append(Bref)

In [ ]:
SS1_RGBimg1

array([[[219, 189, 139],
        [218, 188, 138],
        [217, 187, 137]],

       [[220, 190, 140],
        [219, 189, 139],
        [219, 189, 139]],

       [[219, 189, 139],
        [218, 188, 138],
        [218, 188, 138]]], dtype=uint8)

In [ ]:
list_total

[218.55555555555554, 188.55555555555554, 138.55555555555554]

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img1
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2050:2051])

In [ ]:
SS1_RGBimg1

array([[[220, 190, 140]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img1
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2051:2052])

In [ ]:
SS1_RGBimg1

array([[[219, 189, 139]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img1
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2052:2053])

In [ ]:
SS1_RGBimg1

array([[[219, 189, 139]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1803,1753:1756])
S5refA1_1 = np.reshape(SS1_RGBimg1,(3*3, 3))  
S5refA1_3 = np.array(S5refA1_1)
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()

list_total = list()
list_total.append(Rref)
list_total.append(Gref)
list_total.append(Bref)

In [ ]:
SS1_RGBimg1

array([[[227, 209, 173],
        [228, 210, 174],
        [226, 208, 172]],

       [[227, 209, 173],
        [227, 209, 173],
        [226, 208, 172]],

       [[226, 208, 172],
        [226, 208, 172],
        [226, 208, 172]]], dtype=uint8)

In [ ]:
list_total

[226.55555555555554, 208.55555555555554, 172.55555555555554]

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1803,2050:2053])
S5refA1_1 = np.reshape(SS1_RGBimg1,(3*3, 3))  
S5refA1_3 = np.array(S5refA1_1)
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()

list_total = list()
list_total.append(Rref)
list_total.append(Gref)
list_total.append(Bref)

In [ ]:
SS1_RGBimg1

array([[[228, 202, 151],
        [226, 200, 149],
        [231, 205, 154]],

       [[229, 203, 152],
        [235, 209, 158],
        [235, 209, 158]],

       [[231, 205, 154],
        [234, 208, 157],
        [229, 203, 152]]], dtype=uint8)

In [ ]:
list_total

[230.88888888888889, 204.88888888888889, 153.88888888888889]

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2050:2051])

In [ ]:
SS1_RGBimg1

array([[[229, 203, 152]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2051:2052])

In [ ]:
SS1_RGBimg1

array([[[235, 209, 158]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1801,1750:1751])

In [ ]:
SS1_RGBimg1

array([[[216, 191, 150]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1801,1751:1752])

In [ ]:
SS1_RGBimg1

array([[[216, 191, 150]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1801,1752:1753])

In [ ]:
SS1_RGBimg1

array([[[215, 190, 149]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,1752:1753])

In [ ]:
SS1_RGBimg1

array([[[215, 190, 149]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,1751:1752])

In [ ]:
SS1_RGBimg1

array([[[216, 191, 150]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,1750:1751])

In [ ]:
SS1_RGBimg1

array([[[217, 192, 151]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,1750:1751])

In [ ]:
SS1_RGBimg1

array([[[217, 192, 151]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,1751:1752])

In [ ]:
SS1_RGBimg1

array([[[216, 191, 150]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,1752:1753])

In [ ]:
SS1_RGBimg1

array([[[215, 190, 149]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1801,2050:2051])

In [ ]:
SS1_RGBimg1

array([[[208, 181, 136]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1801,2051:2052])

In [ ]:
SS1_RGBimg1

array([[[210, 183, 138]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1800:1801,2052:2053])

In [ ]:
SS1_RGBimg1

array([[[209, 182, 137]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2050:2051])

In [ ]:
SS1_RGBimg1

array([[[208, 181, 136]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2051:2052])

In [ ]:
SS1_RGBimg1

array([[[209, 182, 137]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1801:1802,2052:2053])

In [ ]:
SS1_RGBimg1

array([[[210, 183, 138]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,2050:2051])

In [ ]:
SS1_RGBimg1

array([[[206, 179, 134]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,2051:2052])

In [ ]:
SS1_RGBimg1

array([[[207, 180, 135]]], dtype=uint8)

In [ ]:
list_total_S1 = list()
list_total_S11 = list()
SS1 = img2
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1802:1803,2052:2053])

In [ ]:
SS1_RGBimg1

array([[[209, 182, 137]]], dtype=uint8)

In [ ]:
#D3 A2
list_total_S1 = list()
list_total_S11 = list()
SS1 = img1
full_path_to_file2 = os.path.join(SS1) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(SS1)
SS1_RGB_img = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
SS1_RGBimg1 =  np.array(SS1_RGB_img[1763:1764,1776:1777])  
SS1_RGBimg2 =  np.array(SS1_RGB_img[1765:1766,1750:1751])  
SS1_RGBimg3 =  np.array(SS1_RGB_img[1773:1774,1790:1791]) 
SS1_RGBimg4 =  np.array(SS1_RGB_img[1789:1790,1768:1769])   
list_total_S1.append(SS1_RGBimg1)
list_total_S1.append(SS1_RGBimg2)
list_total_S1.append(SS1_RGBimg3)
list_total_S1.append(SS1_RGBimg4)

SS1_RGBimg5 =  np.array(SS1_RGB_img[1759:1760,2078:2079])  
SS1_RGBimg6 =  np.array(SS1_RGB_img[1765:1766,2056:2057])  
SS1_RGBimg7 =  np.array(SS1_RGB_img[1777:1778,2066:2067]) 
SS1_RGBimg8 =  np.array(SS1_RGB_img[1783:1784,2094:2095])   
list_total_S11.append(SS1_RGBimg5)
list_total_S11.append(SS1_RGBimg6)
list_total_S11.append(SS1_RGBimg7)
list_total_S11.append(SS1_RGBimg8)

In [ ]:
list_total_S1

In [ ]:
list_total_S11

In [ ]:
img22 = cv2.imread(img2)
RGB_img2= cv2.cvtColor(img22, cv2.COLOR_BGR2RGB)

In [ ]:
plt.imshow(RGB_img2)

In [ ]:
#D3 B4
list_total_S2 = list()
list_total_S22 = list()
SS2 = img2
full_path_to_file2 = os.path.join(SS2) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee2 = cv2.imread(SS2)
SS2_RGB_img = cv2.cvtColor(imagee2, cv2.COLOR_BGR2RGB)
SS2_RGBimg1 =  np.array(SS2_RGB_img[1827:1828,1761:1762])  
SS2_RGBimg2 =  np.array(SS2_RGB_img[1825:1826,1783:1784])  
SS2_RGBimg3 =  np.array(SS2_RGB_img[1849:1850,1779:1780]) 
SS2_RGBimg4 =  np.array(SS2_RGB_img[1857:1856,1745:1746])   
list_total_S2.append(SS2_RGBimg1)
list_total_S2.append(SS2_RGBimg2)
list_total_S2.append(SS2_RGBimg3)
list_total_S2.append(SS2_RGBimg4)


SS2_RGBimg5 =  np.array(SS2_RGB_img[1847:1848,2066:2067])  
SS2_RGBimg6 =  np.array(SS2_RGB_img[1845:1846,2080:2081])  
SS2_RGBimg7 =  np.array(SS2_RGB_img[1847:1846,2040:2041]) 
SS2_RGBimg8 =  np.array(SS2_RGB_img[1647:1648,1763:1764])   
list_total_S22.append(SS2_RGBimg5)
list_total_S22.append(SS2_RGBimg6)
list_total_S22.append(SS2_RGBimg7)
list_total_S22.append(SS2_RGBimg8)

In [ ]:
SS2_RGBimg4

In [ ]:
list_total_S2

In [ ]:
list_total_S22

In [ ]:
img33 = cv2.imread(img3)
RGB_img3= cv2.cvtColor(img33, cv2.COLOR_BGR2RGB)

In [ ]:
plt.imshow(RGB_img3)

In [ ]:
#D3 D3
list_total_S3 = list()
list_total_S33 = list()
SS3 = img3
full_path_to_file2 = os.path.join(SS3) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee3 = cv2.imread(SS3)
SS3_RGB_img = cv2.cvtColor(imagee3, cv2.COLOR_BGR2RGB)
SS3_RGBimg1 =  np.array(SS3_RGB_img[1756:1757,1762:1763])  
SS3_RGBimg2 =  np.array(SS3_RGB_img[1758:1759,1784:1785])  
SS3_RGBimg3 =  np.array(SS3_RGB_img[1790:1791,1750:1751]) 
SS3_RGBimg4 =  np.array(SS3_RGB_img[1778:1779,1784:1783])   
list_total_S3.append(SS3_RGBimg1)    
list_total_S3.append(SS3_RGBimg2)
list_total_S3.append(SS3_RGBimg3)
list_total_S3.append(SS3_RGBimg4)

SS3_RGBimg5 =  np.array(SS3_RGB_img[1770:1771,2068:2069])  
SS3_RGBimg6 =  np.array(SS3_RGB_img[1766:1767,2046:2047])  
SS3_RGBimg7 =  np.array(SS3_RGB_img[1788:1789,2050:2051]) 
SS3_RGBimg8 =  np.array(SS3_RGB_img[1792:1793,2074:2075])   
list_total_S33.append(SS3_RGBimg5)
list_total_S33.append(SS3_RGBimg6)
list_total_S33.append(SS3_RGBimg7)
list_total_S33.append(SS3_RGBimg8)

In [ ]:
list_total_S3

In [ ]:
list_total_S33

In [ ]:
img44 = cv2.imread(img4)
RGB_img4= cv2.cvtColor(img44, cv2.COLOR_BGR2RGB)

In [ ]:
plt.imshow(RGB_img4)

In [ ]:
#D3 A1
list_total_S4 = list()
list_total_S44 = list()
SS4 = img4
full_path_to_file2 = os.path.join(SS4) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee4 = cv2.imread(SS4)
SS4_RGB_img = cv2.cvtColor(imagee4, cv2.COLOR_BGR2RGB)
SS4_RGBimg1 =  np.array(SS4_RGB_img[1765:1766,1757:1758])  
SS4_RGBimg2 =  np.array(SS4_RGB_img[1775:1776,1769:1770])  
SS4_RGBimg3 =  np.array(SS4_RGB_img[1801:1802,1741:1742]) 
SS4_RGBimg4 =  np.array(SS4_RGB_img[1779:1780,1781:1782])   
list_total_S4.append(SS4_RGBimg1)
list_total_S4.append(SS4_RGBimg2)
list_total_S4.append(SS4_RGBimg3)
list_total_S4.append(SS4_RGBimg4)

SS4_RGBimg5 =  np.array(SS4_RGB_img[1773:1774,2076:2077])  
SS4_RGBimg6 =  np.array(SS4_RGB_img[1763:1764,2042:2043])  
SS4_RGBimg7 =  np.array(SS4_RGB_img[1769:1770,2080:2081]) 
SS4_RGBimg8 =  np.array(SS4_RGB_img[1789:1790,2068:2069])   
list_total_S44.append(SS4_RGBimg5)
list_total_S44.append(SS4_RGBimg6)
list_total_S44.append(SS4_RGBimg7)
list_total_S44.append(SS4_RGBimg8)

In [ ]:
list_total_S4

In [ ]:
list_total_S44